### ISSUE TITLE
Metoda dump w klasie MapVisualizer

### ISSUE THREAD

**Issue by MieszkoMakuch** [apohllo/obiektowe-lab#2]
Metoda `dump` w klasie `MapVisualizer` (obiektowe-lab/lab4/MapVisualizer.java) nie bierze pod uwagę parametru `x` przy wyznaczaniu lewego dolnego rogu - `lowerLeft.x`

Myślę, że w lini 29 zamiast:
`for (int j = lowerLeft.y; j < upperRight.x + 1; j++) {`
powinno być:
`for (int j = lowerLeft.x; j < upperRight.x + 1; j++) {`

i w lini 32 zamiast:
`for (int j = lowerLeft.y; j <= upperRight.x + 1; j++) {`
powinno być:
`for (int j = lowerLeft.x; j <= upperRight.x + 1; j++) {`

**Comment by apohllo** [comment]
Tak, jest błąd. Dziękuję za zwrócenie uwagi. Naprawione.
