### ISSUE TITLE
Histroria zwierząt

### ISSUE THREAD

**Issue by Petroniuss** [apohllo/obiektowe-lab#21]
"wskazać pojedyncze zwierzę, w celu śledzenia jego historii:
określenie liczby wszystkich dziedzi, po n-epokach,
określenia liczby wszystkich potomków, po n-epokach" - chodzi tutaj o liczbę potomków w aktualnej epoce czy może oczekujemy na wprowadzenie liczby n jako epoki dla której mamy pokazać ile wtedy dane zwierze miało potomków ??

**Comment by apohllo** [comment]
chodzi o drugą wersję
