### ISSUE TITLE
Ostrzeżenie przed kodowaniem UTF-16 w .gitignore 

### ISSUE THREAD

**Issue by wlgs** [apohllo/obiektowe-lab#41]
W PowerShellu wykonując polecenie `echo 'out' > .gitignore` stworzony plik `.gitignore` będzie zakodowany w UTF-16, którego git nie będzie rozumiał (w przeciwieństwie do UTF-8 dla `echo` w CMD). 
Przydałby się warning przed PowerShellem w **git-wprowadzenie** w sekcji **Przydatne informacje** w punkcie 2 by oszczędzić sporo czasu szukania rozwiązania problemu z niewczytującym się `.gitignore`

**Comment by apohllo** [comment]
OK.

**Comment by apohllo** [comment]
Zrobione.
